/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include <eth_gateway.h>
#include "main.h"
#include "eth.h"
#include "usart.h"
#include "gpio.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"

#include "gateway_config.h"
#include "gateway_types.h"
#include "diag.h"
#include "mb_slave.h"
#include "mb_master.h"
#include "mb_crc16.h"
#include "eth_gateway.h"
#include "cli.h"
#include "gateway.h"

#include <string.h>
#include <stdint.h>

/* =========================================================================
   Modbus Slave register bank (application data)
   ========================================================================= */
static uint16_t s_holding_regs[GW_MB_HOLDING_REG_COUNT];

static const MB_Slave_RegBank_t s_reg_bank = {
    .holding_regs  = s_holding_regs,
    .holding_count = GW_MB_HOLDING_REG_COUNT,
    .holding_start = GW_MB_HOLDING_REG_START,
};

/* =========================================================================
   UART RX — raw byte queue (ISR → UartRxTask)
   ========================================================================= */
static QueueHandle_t xUartByteQueue = NULL;
static uint8_t s_rx_byte;          /* single-byte DMA target */

/* =========================================================================
   Modbus frame queue (UartRxTask → ModbusParserTask)
   ========================================================================= */
static QueueHandle_t xModbusFrameQueue = NULL;

/* =========================================================================
   Forward declarations
   ========================================================================= */
static void Task_UartRx       (void *pvParameters);
static void Task_ModbusParser (void *pvParameters);
static void Task_Watchdog     (void *pvParameters);
void SystemClock_Config(void);
void MX_FREERTOS_Init(void);

/* =========================================================================
   HAL slave TX callback — called from mb_slave when response is ready.
   Routes to gateway for Ethernet wrapping.
   ========================================================================= */
static void prv_MbSlaveResponseCb(const uint8_t *buf, uint16_t len, void *ctx)
{
    (void)ctx;

    /* Transmit back on RS-485 */
    /* RS-485 DE high → transmit */
    HAL_GPIO_WritePin(GW_RS485_DE_PORT, GW_RS485_DE_PIN, GPIO_PIN_SET);
    HAL_UART_Transmit(&huart3, buf, len, 100);
    HAL_GPIO_WritePin(GW_RS485_DE_PORT, GW_RS485_DE_PIN, GPIO_PIN_RESET);

    DIAG_Increment(&gDiag.mb_frames_tx);
}

/* =========================================================================
   Application entry point
   ========================================================================= */
int main(void)
{
    /* HAL and clock setup — generated by CubeMX, preserved exactly */
    HAL_Init();
    SystemClock_Config();

    /* Peripheral init */
    MX_GPIO_Init();
    MX_ETH_Init();         /* From eth.c — sets up DMA descriptors, MAC   */
    MX_USART3_UART_Init(); /* Debug / CLI UART                             */

    /* ---- Application layer init ---- */
    DIAG_Init();

    /* Modbus Slave */
    memset(s_holding_regs, 0, sizeof(s_holding_regs));
    MB_Slave_Init(GW_MB_SLAVE_ID, &s_reg_bank,
                  prv_MbSlaveResponseCb, NULL);

    /* Modbus Master (slave 1, FC 03 — adjust per deployment) */
    MB_Master_Init(1U, MB_FC_READ_HOLDING_REGS);

    /* Ethernet Gateway */
    ETH_GW_Init();

    /* Translation layer */
    Gateway_Init();

    /* CLI */
    CLI_Init();

    /* ---- Byte-level UART RX queue ---- */
    xUartByteQueue    = xQueueCreate(GW_UART_BYTE_QUEUE_LEN, sizeof(uint8_t));
    xModbusFrameQueue = xQueueCreate(GW_MODBUS_FRAME_QUEUE_LEN,
                                     sizeof(GW_ModbusFrameMsg_t));
    configASSERT(xUartByteQueue    != NULL);
    configASSERT(xModbusFrameQueue != NULL);

    /* Arm UART RX interrupt before starting scheduler */
    HAL_UART_Receive_IT(&huart3, &s_rx_byte, 1);

    /* ---- Create RTOS tasks ---- */
  //  xTaskCreate(Task_Watchdog,     "Watchdog",  GW_STACK_WATCHDOG,
  //            NULL, GW_PRIO_WATCHDOG, NULL);

    xTaskCreate(Task_UartRx,       "UartRx",    GW_STACK_UART_RX,
                NULL, GW_PRIO_UART_RX, NULL);

    xTaskCreate(Task_ModbusParser, "MbParser",  GW_STACK_MODBUS_PARSER,
                NULL, GW_PRIO_MODBUS_PARSER, NULL);

    xTaskCreate(Gateway_Task,      "Gateway",   GW_STACK_GATEWAY,
                NULL, GW_PRIO_GATEWAY, NULL);

    xTaskCreate(ETH_GW_RxTask,     "EthRx",     GW_STACK_ETH_RX,
                NULL, GW_PRIO_ETH_RX, NULL);

    xTaskCreate(ETH_GW_TxTask,     "EthTx",     GW_STACK_ETH_TX,
                NULL, GW_PRIO_ETH_TX, NULL);

    xTaskCreate(DIAG_Task,         "Diag",      GW_STACK_DIAG,
                NULL, GW_PRIO_DIAG, NULL);

    xTaskCreate(CLI_Task,          "CLI",       GW_STACK_CLI,
                NULL, GW_PRIO_CLI, NULL);

    /* Start Ethernet DMA after tasks are created */
    ETH_GW_Start();

    /* Hand control to FreeRTOS — never returns */
    vTaskStartScheduler();

    /* Should never reach here */
    Error_Handler();
    return 0;
}

/* =========================================================================
   TASK: UartRxTask
   Collects raw bytes from the ISR queue and assembles complete Modbus frames.
   Frame boundary detection: 3.5-character silence (GW_MODBUS_FRAME_TIMEOUT_MS).
   ========================================================================= */
static void Task_UartRx(void *pvParameters)
{
    (void)pvParameters;

    uint8_t             byte;
    GW_ModbusFrameMsg_t frame;
    uint16_t            frame_idx     = 0;
    TickType_t          last_rx_tick  = 0;

    memset(&frame, 0, sizeof(frame));

    for (;;)
    {
        TickType_t timeout = (frame_idx > 0)
            ? pdMS_TO_TICKS(GW_MODBUS_FRAME_TIMEOUT_MS)
            : portMAX_DELAY;

        BaseType_t got = xQueueReceive(xUartByteQueue, &byte, timeout);

        if (got == pdTRUE)
        {
            DIAG_Increment(&gDiag.uart_rx_bytes);

            if (frame_idx < GW_MODBUS_MAX_FRAME_LEN)
            {
                frame.data[frame_idx++] = byte;
                last_rx_tick = xTaskGetTickCount();
            }
            else
            {
                /* Frame too long — overflow */
                frame_idx = 0;
                DIAG_Increment(&gDiag.uart_rx_overflow);
            }
        }
        else
        {
            /* Timeout expired while mid-frame → treat as frame end */
            if (frame_idx >= MB_RTU_MIN_FRAME_LEN)
            {
                frame.length       = frame_idx;
                frame.timestamp_ms = xTaskGetTickCount();

                if (xQueueSend(xModbusFrameQueue, &frame, 0) != pdTRUE)
                    DIAG_Increment(&gDiag.queue_overflow);
            }
            frame_idx = 0;
            memset(frame.data, 0, sizeof(frame.data));
        }
    }
}

/* =========================================================================
   TASK: ModbusParserTask
   Validates CRC, classifies frame (slave request or master response),
   dispatches to the Gateway translation layer.
   ========================================================================= */
static void Task_ModbusParser(void *pvParameters)
{
    (void)pvParameters;

    GW_ModbusFrameMsg_t frame;
    GW_MbEvent_t        evt;

    for (;;)
    {
        if (xQueueReceive(xModbusFrameQueue, &frame,
                          portMAX_DELAY) != pdTRUE) continue;

        DIAG_Increment(&gDiag.mb_frames_rx);

        /* CRC validation */
        if (!MB_CRC16_Verify(frame.data, frame.length))
        {
            DIAG_Increment(&gDiag.mb_crc_errors);

            evt.type = MB_EVT_CRC_ERROR;
            Gateway_PostModbusEvent(&evt);
            continue;
        }

        /* --- Determine if this is a slave request addressed to us --- */
        uint8_t slave_id = frame.data[0];
        uint8_t fc       = frame.data[1];

        memset(&evt, 0, sizeof(evt));
        evt.slave_id      = slave_id;
        evt.function_code = fc;
        memcpy(evt.payload, frame.data, frame.length);
        evt.payload_len   = frame.length;

        if (slave_id == GW_MB_SLAVE_ID || slave_id == 0U)
        {
            /* Process as slave: mb_slave.c will call the TX callback */
            MB_Slave_ProcessFrame(frame.data, frame.length);
            evt.type = MB_EVT_SLAVE_REQUEST;
        }
        else
        {
            /* Could be a master response or a frame for another slave — forward */
            evt.type = MB_EVT_MASTER_RESPONSE;
        }

        Gateway_PostModbusEvent(&evt);
    }
}

/* =========================================================================
   TASK: WatchdogTask
   ========================================================================= */
static void Task_Watchdog(void *argument)
{
    for (;;)
    {
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

/* =========================================================================
   UART RX ISR Callback
   Called from HAL in IRQ context — keep it fast.
   ========================================================================= */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == GW_MODBUS_UART_INSTANCE)
    {
        BaseType_t woken = pdFALSE;

        if (xQueueSendFromISR(xUartByteQueue, &s_rx_byte, &woken) != pdTRUE)
        {
            /* Safe to call Atomic_Increment from ISR */
            gDiag.uart_rx_overflow++;
        }

        /* Re-arm for next byte */
        HAL_UART_Receive_IT(&huart3, &s_rx_byte, 1);

        portYIELD_FROM_ISR(woken);
    }
}



/* =========================================================================
   Stack overflow hook
   ========================================================================= */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    BSP_LED_On(LED_RED);
    __disable_irq();
    while (1);
}


/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI48|RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_BYPASS_DIGITAL;
  RCC_OscInitStruct.HSI48State = RCC_HSI48_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLL1_SOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 5;
  RCC_OscInitStruct.PLL.PLLN = 100;
  RCC_OscInitStruct.PLL.PLLP = 2;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1_VCIRANGE_2;
  RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1_VCORANGE_WIDE;
  RCC_OscInitStruct.PLL.PLLFRACN = 0;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_PCLK3;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure the programming delay
  */
  __HAL_FLASH_SET_PROGRAM_DELAY(FLASH_PROGRAMMING_DELAY_2);
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  Period elapsed callback in non blocking mode
  * @note   This function is called  when TIM5 interrupt took place, inside
  * HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment
  * a global variable "uwTick" used as application time base.
  * @param  htim : TIM handle
  * @retval None
  */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  /* USER CODE BEGIN Callback 0 */

  /* USER CODE END Callback 0 */
  if (htim->Instance == TIM5)
  {
    HAL_IncTick();
  }
  /* USER CODE BEGIN Callback 1 */

  /* USER CODE END Callback 1 */
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
